blank_issues_enabled: false
contact_links:
  - name: ❓ Questions & Discussions
    url: https://github.com/0xstern/payload-address-field/discussions
    about: Ask questions and discuss ideas with the community
  - name: 📖 Documentation
    url: https://github.com/0xstern/payload-address-field#readme
    about: Read the documentation
